### ISSUE TITLE
myget.org is down, running nuget-inspector fails; is there an alternative?

### ISSUE THREAD

**Issue by sschuberth** [nexB/nuget-inspector#48]
Apparently myget.org has been down for some time, causing any nuget-inspector runs to [fail](https://github.com/oss-review-toolkit/ort/actions/runs/5670614327/job/15365893900?pr=7339#step:6:2346). Is there any known work-around for this?

**Comment by pombredanne** [comment]
@sschuberth you wrote:

> Apparently myget.org has been down for some time, causing any nuget-inspector runs to fail. Is there any known work-around for this?

Are you sure? ..... I am quite certain that myget could not be causing "any nuget-inspector runs" to fail as myget is not something that is part of anything standard in nuget-inspector. 

Now if you have a nuget.config pointing to a dead website, this would be causing any runs (such as a myget.org) to fail **as they should IMHO** as otherwise we would get incorrect dependency resolution.

To get the ORT tests to pass -- assuming this is the only issue -- you should remove myget from the test suite in the nuget.config at  https://github.com/oss-review-toolkit/ort/blob/d8a2ac61c1d684554eb351d292a1919183b6827d/plugins/package-managers/nuget/src/funTest/assets/dotnet/subProjectTestWithNuGetConfig/NuGetConfig/nuget.config and possibly other nuget.config and adjust your expected results accordingly.

**Comment by sschuberth** [comment]
> Are you sure? ..... I am quite certain that myget could not be causing "any nuget-inspector runs" to fail as myget is not something that is part of anything standard in nuget-inspector.

You're right. I was assuming *nuget-inspector* to be using https://myget.org/ internally, but in fact it really only comes from a `nuget.config`'s package source.

> To get the ORT tests to pass -- assuming this is the only issue -- you should remove myget from the test suite in the nuget.config

Yes, that was the only issue I wanted to solve, and following your hint [did the trick](https://github.com/oss-review-toolkit/ort/pull/7340). Thanks and sorry for the noise!
